# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0015_auto_20180926_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaldeferreddispatch',
            name='done',
            field=models.BooleanField(default=None, null=True),
        ),
    ]

